name: Deploy APT Frontend Static to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Отладка структуры после клонирования
      - name: Debug directory structure
        run: ls -R .

      # 3. Настройка GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # 4. Загрузка статических файлов из папки core
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: core

      # 5. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
